def welcome():  
  print("\n")
  print("---Welcome to Memo'd. The leading provider of subconscious memory services.---")
  print("\n")
  print("It looks like your account is registered as shared")
  print("Checking subconscious of Buzz.....")
  print("Checking subconscious of Merla.....")
  print("Checking subconscious of Varik.....")
  print("\n")
  print("What would you like to remember?")
  print("\n")